
{
  air_date: "2016-10-11",
  episodes: [
  {
  release: "2016-10-11",
  episode: 1,
  episode_type: "standard",
  title: "The Hose or the Animal",
 overview: "Severide and Stella search for Grant, who's AWOL from Chicago Med. Dawson questions her career path. Casey's relationship with his political consultant cools. Borrelli's anger at Boden over his brother's death boils over. Mouch and Brett partner on a new venture.",
  runtime: 42,
  },
 {
  release: '2016-10-18',
  episode: 2,
  episode_type: "standard",
  title: "A Real Wake-Up Call",
  overview: "Casey and Dawson find themselves in the midst a potential political mess. Stella has to make a big decision about her ex-beau. The squad responds to an auto accident. Severide befriends a socialite. Brett and Mouch set aside their writing differences for the greater good.",
  },
  {
  release: "2016-10-25",
  episode: 3,
  episode_type: "standard",
  title: "Scorched Earth",
  overview: "Casey seeks help with a personal matter from Susan Weller. A rich party guy wants Severide to travel with him. Stella tries to help a sick street kid. Otis and Herrmann share their concerns about Molly's lack of customers.",
  runtime: 42,
  },
  {
  release: "2016-11-01",
  episode: 4,
  episode_type: "standard",
  title: "Nobody Else Is Dying Today",
  overview: "Lt. Casey finds himself in a bad spot when a forklift accidentally pierces a tank storing acid. Casey is forced to use extreme measures to help a father and daughter in peril. Dawson and Brett respond to an elderly woman who has a difficult senior advocate. Mouch and Brett continue with their secret project. Otis shares some exciting news as he prepares himself for an unusual expedition.",
  runtime: 42,
  },
  {
 release: "2016-11-15",
  episode: 5,
  episode_type: "standard",
  id: 1230656,
  title: "I Held Her Hand",
  overview: "Lt. Casey is unable to rescue a woman who becomes trapped inside her burning greystone, prompting him and Lt. Severide to butt heads over the husband's role in the tragedy. Herrmann is on a mission to catch a mystery tagger that keeps targeting their firehouse and Boden gets a surprise visitor. Meanwhile, Dawson and Brett respond to a 16-year-old boy who was injured during a romantic homecoming proposal.",
  runtime: 42,
  },
  {
  release: "2016-11-22",
  episode: 6,
  episode_type: "standard",
  id: 1230657,
  title: "That Day",
  overview: "While responding to a call in the field, Dawson accidentally hits a pedestrian who stepped in front of the ambulance, and is left to deal with the repercussions. Lt. Casey and Lt. Severide disagree and continue to investigate an arson case while Chief Boden is left to decide whether to attend an important function in New York. Elsewhere, in hopes of preparing him for a possible promotion, Lt. Casey puts Herrmann at the helm for a shift so he can discover firsthand what his superiors deal with.",
  runtime: 42,
  },
  {
  release: "2016-11-29",
  episode: 7,
  episode_type: "standard",
  id: 1230658,
  title: "Lift Each Other",
  overview: "It's a family reunion when Dawson and Antonio's mother and father come to Chicago for their big anniversary party, but things quickly turn south. When a deep secret comes to the surface involving his stepson James, Chief Boden decides to take matters into his own hands. Meanwhile, Casey tries to save a young boy during a harrowing call to a warehouse and Otis and Kidd become competitive at the mud-hundred race.",
  runtime: 42,
  },
  {
  release: "2016-12-06",
  episode: 8,
  episode_type: "standard",
  id: 1230659,
  title: "One Hundred",
  overview: "Lt. Casey and Dawson apply for permanent adoption of Louie, but quickly discover a hurdle. Firefighter-turned-medical student Jeff Clarke approaches Lt. Severide with an interesting proposition. With hopes of reinvigorating business at the bar, Otis convinces a skeptical Herrmann to throw a bash in celebration of the milestone 100th anniversary of Molly's, but not without complications.",
  runtime: 42,
  },
  {
  release: "2017-01-03",
  episode: 9,
  episode_type: "standard",
  id: 1249307,
  title: "Some Make It, Some Don't (I)",
  overview: "Dawson and Casey deal with legal matters in hopes of remaining Louie's legal guardians. Severide continues in his efforts for a bone marrow procedure to help Anna, but when things don't go as planned, he finds himself slipping back into old habits. Meanwhile, Brett opens up to Dawson and members of Firehouse 51 become competitive, much to the dismay of Chief Boden. The crossover continues on Chicago P.D. S04E09 Don't Bury This Case (II).",
  runtime: 42,
  },
  {
  release: "2017-01-17",
  episode: 10,
  episode_type: "standard",
  id: 1253348,
  title: "The People We Meet",
  overview: "Severide agrees to a bone marrow donation but a work accident throws everything into flux. Casey and Dawson try to find harmony at home. Meanwhile, Otis and Mouch decide to film a PSA encouraging people to join the Chicago Fire Department but hit a creative wall in the process.",
  runtime: 42,
  },
  {
  release: "2017-01-24",
  episode: 11,
  episode_type: "standard",
  id: 1253349,
  title: "Who Lives and Who Dies",
  overview: "Dawson finds it hard to keep her emotions in check during an ambo run involving a pregnant teen. Elsewhere, the firehouse is called to the site of a building fire and Casey is forced to make a split-second decision when two victims are each need of life-saving assistance. In the aftermath, Casey is left to deal with the repercussions. Meanwhile, Severide shares a bond with Anna, as she makes her recovery.",
  runtime: 42,
  },
  {
  release: "2017-02-07",
  episode: 12,
  episode_type: "standard",
  id: 1253350,
  title: "An Agent of the Machine",
  overview: "The team is on high alert when a previous incident during a fire call leaves a dangerous man on the loose with a vendetta to target Lt. Casey and Firehouse 51, and prompts CPD to step in. Dennis Mack, a buddy firefighter of Severide's father, comes to town to shadow the squad but may have ulterior motives. Meanwhile, Brett and Antonio's relationship hits some bumps in the road when his ex-wife Laura surfaces and Casey has a present for Dawson.",
  runtime: 42,
  },
  {
  release: "2017-02-14",
  episode: 13,
  episode_type: "standard",
  id: 1260477,
  title: "Trading in Scuttlebutt",
  overview: "When truck and squad are summoned to the scene of a dangerous accident, Chief Boden makes a split-second decision that overrides Chief Anderson, the incident commander whose house was the first to respond to the call. Feeling his authority was undercut and his reputation damaged, Anderson uses his power to make things miserable for Boden and all of House 51 feels the repercussions.",
  runtime: 42,
  },
  {
  release: "2017-02-21",
  episode: 14,
  episode_type: "standard",
  id: 1262860,
  title: "Purgatory",
  overview: "After exercising his disdain and authority over Chief Boden, Chief Anderson reassigns members of 51 to various houses around town, citing the need for improvement. The ramifications are felt by the crew, who are left to make the best of their respective situations in their new surroundings.",
  runtime: 42,
  },
  {
  release: "2017-03-01",
  episode: 15,
  episode_type: "standard",
  id: 1266970,
  title: "Deathtrap (I)",
  overview: "Truck and squad are called to aid in a massive all-city response when an old, ill-equipped factory-turned live/work space quickly turns into a firestorm, trapping countless unsuspecting victims. The dire situation quickly turns personal when it is discovered that one of Chicago PD's own has a family member at the scene. The crossover continues on Chicago P.D. S04E016 Emotional Proximity (II) and Chicago Justice S01E01 Fake (III).",
  runtime: 42,
  },
  {
  release: "2017-03-21",
  episode: 16,
  episode_type: "standard",
  id: 1278924,
  title: "Telling Her Goodbye",
  overview: "When a turf war escalates, members of truck and squad find themselves caught in the middle as unsuspecting hostages when a group of armed gang members take cover and assume control over Firehouse 51.",
  runtime: 42,
  },
  {
  release: "2017-03-28",
  episode: 17,
  episode_type: "standard",
  id: 1287181,
  title: "Babies and Fools",
  overview: "When similar car accidents uncover the fact that someone may be targeting innocent people, a determined Dawson takes matters into her own hands to help push things along. Severide does everything he can to make Anna feel welcome in her new Chicago surroundings. Herrmann, Kidd and Dawson decide to have Molly's included as a stop in this year's pub crawl. Meanwhile, Casey tends to his Alderman's duties when a persistent constituent asks for his help in resolving an issue.",
  runtime: 42,
  },
  {
  release: "2017-04-04",
  episode: 18,
  episode_type: "standard",
  id: 1290020,
  title: "Take a Knee",
  overview: "Casey discovers a new crack house on the block that is harboring a female junkie. Dawson and Brett get assigned a new trainee for the shift. Meanwhile, Severide gets an unexpected visit from his father and Herrmann deals with family issues when his son gets into trouble at school.",
  runtime: 42,
  },
  {
  release: "2017-04-25",
  episode: 19,
  episode_type: "standard",
  id: 1303164,
  title: "Carry Their Legacy",
  overview: "When the squad's rig breaks down in the field, Casey reunites with his old friend and colleague Jason Kannell from Squad 6. Dawson and Brett serve their time in retraining. Severide tries to remedy what is going on with Anna and finds support from unlikely sources. As Connie returns from her family engagement, the crew lays bets on how long her temporary replacement Marcy will last.",
  runtime: 42,
  },
  {
  release: "2017-05-02",
  episode: 20,
  episode_type: "standard",
  id: 1303165,
  title: "Carry Me",
  overview: "Casey goes to drastic measures to help his friend Kannell. Lt. Severide helps an old widow come to terms with letting go, but realizes he may be the one needing help. Otis and Cruz deal with surprises when they find a new roommate to move in. Dawson and Brett get crafty to save a young girl.",
  runtime: 42,
  },
  {
  release: "2017-05-09",
  episode: 21,
  episode_type: "standard",
  id: 1305314,
  title: "Sixty Days",
  overview: "Cruz finds himself in a bad spot when an off-duty incident begins to unravel, prompting Mouch to step in and offer help in hopes of avoiding serious consequences from the CFD. Casey goes head to head with a big politician to get his measure for first responders passed. Lt. Severide makes life difficult for newest team member Jason Kannell and Dawson gets an unexpected visit from her father. ",
  },
  {
  release: "2017-05-16",
  episode: 22,
  episode_type: "finale",
  id: 1308213,
  title: "My Miracle",
  overview: "A dangerous warehouse fire puts truck and squad at risk. Tensions are high for Dawson and Casey when Dawson's father overstays his welcome at their home. Meanwhile, Casey continues to fight for his first responders bill, Mouch makes a serious decision regarding his future and Herrmann goes to tremendous lengths to make a young boy smile.",
  runtime: 42,
 },
  ]
  
  }